# Generated by Django 3.2 on 2023-04-22 12:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='scheduled_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 6, 12, 14, 17, 706923, tzinfo=utc)),
        ),
    ]
