# Generated by Django 3.2 on 2023-04-23 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_event_scheduled_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='scheduled_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 8, 46, 56, 767319)),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Scheduled'), (2, 'Cancelled')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Scheduled'), (2, 'Cancelled')], default=0),
        ),
    ]
